##########################################
### SAMPLE
##########################################

# User
userId: "<samplify userId>"  # e.g. userid: "kolart"
userEmail: "<userEmail>"     # e.g. userEmail: "kolart@uw.edu"

# Sample
sampleDirectory: "<full path to sample directory>"    # e.g. sampleDirectory: "/net/nwgc/vol1/data/processed/samples/123456/WHOLE_GENOME"
sampleId: <samplify sampleId>                         # e.g sampleId: 123456

# Target
sequencingTarget: "<name of sequencing target>"   	  # e.g. sequencingTarget: "nimblegen_solution_V2refseq_2010"
targetListFile: "<full path to target .list file>"    # e.g. targetListFile: "/net/nwgc/vol1/references/human/hg19/targets/nimblegen_solution_V2refseq_2010/nimblegen_solution_V2refseq_2010.hg19.list"

# Reference Genome
referenceGenome: "<full path to reference genome fasta>"    # e.g. referenceGenome: "/net/nwgc/vol1/references/human/hg19/genome/assembly_bwa_0.7.15/hs37d5.fa"
dbSnp: "<full path to dbSnp file>"                          # e.g. dbSnp: "/net/nwgc/vol1/references/human/snps/dbSNP/dbSNP138.vcf"

# Bam  
bam: "<full path to the bam file from which to call variants>"  # e.g.  bam: /net/nwgc/vol1/home/kolart/pacbio_merged_test.bam   

# Optional (Already defaulted in nextflow.config file to organism=Homo sapiens, isGRC38=false)
organism: "<species other than Homo sapiens>"  # e.g. organism: "Mus musculus"
isGRC38: "<true if grc38>"                     # e.g. isGRC38: true


##########################################
### RabbitMQ
##########################################
rabbitHost: "<name of host for rabbitMQ>"				#e.g rabbitHost: "burnet"
registration_url: "<url to send rabbit message to>"		#e.g.registration_url: "http://burnet.gs.grid.washington.edu/samplify/RegisterPacBioMapMergeQCCompletion"
