##########################################
### SAMPLE
##########################################

# User
userId: "<samplify userId>"  # e.g. userid: "kolart"
userEmail: "<userEmail>"     # e.g. userEmail: "kolart@uw.edu"

# Sample
sampleDirectory: "<full path to sample directory>"    # e.g. sampleDirectory: "/net/nwgc/vol1/data/processed/samples/123456/WHOLE_GENOME"
sampleId: <samplify sampleId>                         # e.g sampleId: 123456

# Reference Genome
starDirectory: "<full path to STAR reference directory>"       # e.g. STARDirectory: "/net/nwgc/vol1/references/human/grc38/genome/STAR/100bp/gencodev30/bundle"
rsemReferencePrefix: "<label used as prefix for rsem files>"   # e.g. rsemReferencePrefix: "rsem_reference"

# Fastqs  
fastq1Files: "<comma separated list of full path to the fastq1 files>"
  # e.g.  fastq1Files: /net/nwgc/vol1/data/processed/flow_cells/HLG2HDMXY/dmux.dir/TCGTACTTGC.TGTTGTGAAG/s_1_1.fastq.gz,/net/nwgc/vol1/data/processed/flow_cells/HLG2HDMXY/dmux.dir/TCGTACTTGC.TGTTGTGAAG/s_2_1.fastq.gz   
fastq2Files: "<comma separated list of full path to the fastq2 files (in same order as fastq1Files>"
  # e.g.  fastq2Files: /net/nwgc/vol1/data/processed/flow_cells/HLG2HDMXY/dmux.dir/TCGTACTTGC.TGTTGTGAAG/s_1_2.fastq.gz,/net/nwgc/vol1/data/processed/flow_cells/HLG2HDMXY/dmux.dir/TCGTACTTGC.TGTTGTGAAG/s_2_2.fastq.gz 

# Read Groups
readGroups: "<comma separated list of read group info (in same order ast fastq1Files)>"
    # e.g.  readGroups: ID:HLG2HDMXY.2.TCGTACTTGC.TGTTGTGAAG CN:UW PL:illumina PU:HLG2HDMXY.2.TCGTACTTGC.TGTTGTGAAG LB:170482 SM:TOR108097 "DT:2023-05-21T10:09:22.912" , ID:HLG2HDMXY.1.TCGTACTTGC.TGTTGTGAAG CN:UW PL:illumina PU:HLG2HDMXY.1.TCGTACTTGC.TGTTGTGAAG LB:170482 SM:TOR108097 "DT:2023-05-21T10:09:16.431"

##########################################
### RabbitMQ
##########################################
rabbitHost: "<name of host for rabbitMQ>"				#e.g rabbitHost: "burnet"
registration_url: "<url to send rabbit message to>"		#e.g.registration_url: "http://burnet.gs.grid.washington.edu/samplify/RegisterPacBioMapMergeQCCompletion"
